<?php

namespace AppBundle\Repository;

/**
 * contactusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactusRepository extends \Doctrine\ORM\EntityRepository
{
}
